### ISSUE TITLE
UX autofocus when file peeking is toggled? [better support for vim]

### ISSUE THREAD

**Issue by asakapab0i** [abierbaum/vscode-file-peek#10]
While in vim when toggling the file peeker I have to click again the window so I can start typing. It would be better to have it auto focus on the editor when toggled.

**Comment by abierbaum** [comment]
@asakapab0i Do you know how to do this through the API.  I agree it would be a great feature.  If you can track it down and put together a pull I would appreciate it.

**Comment by abierbaum** [comment]
Closing for now but would really love a PR to add this.
