### ISSUE TITLE
A user in China could probably meet a problem with css Peek!

### ISSUE THREAD

**Issue by varcharOuYang** [abierbaum/vscode-file-peek#13]
When i was using this great plug-in unit,and i used to jump to css code.All things looked like normal and convenient.But in a bit whlie,i find that the fast reading parts float on the css page's surface and can't shut.
i don't know why i can't shut it.if i meet this issue again,i must unload css Peek and reload it.i guess it maight case with other plug-in unit in HTML's work,but not sure!
My English is poor!Please not laugh with it.-.-  TT

**Comment by abierbaum** [comment]
Not sure I understand the issue.  Can you please check again.  For now closing.
