### ISSUE TITLE
SCSS class symbols not being found/indexed in symbol search

### ISSUE THREAD

**Issue by rkpatel33** [abierbaum/vscode-file-peek#15]
I am trying to jump to a symbol using CMD+T and search for a SCSS/CSS class per the screenshot below but getting no results. Any suggestions on how to debug? I have restarted but seems like my SCSS files are not being indexed somehow.

![image](https://user-images.githubusercontent.com/3799489/40384171-b143fe30-5db7-11e8-9731-675ade5fe618.png)

**Comment by abierbaum** [comment]
This is not a function of file peek.  This is part of vscode itself.
