### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by alefragnani** [abierbaum/vscode-file-peek#4]
First of all, great extension :+1: 

I think you could expand to support any language. Just add a `User Setting`, and each user could define the list of languages that wants to use.

Thanks

**Comment by elypma** [comment]
I complete agree with alefragnani.
Tried to hack it in myself (for python that is), but failed when trying to open the file (although the 'full_path' was valid).

**Comment by alefragnani** [comment]
@elypma to hack, you must update the `package.json` file, adding python to the `activationEvents` and also update the `extension.js` file, adding a Python entry in `PEEK_FILTER` const.
It worked perfectly for me in Pascal files.

**Comment by abierbaum** [comment]
I am very interested in adding something like this.  If anyone has time to submit a pull I would gladly accept it.  Unfortunately I am tied up right now so probably not going to have time to look myself for a few weeks. :(

**Comment by abierbaum** [comment]
@alefragnani I just pushed a new version (1.0.0) of the extension that allows configuring a list of languages that should be supported and a list of file extensions to check for finding.

I think this should give you what you wanted.  Please let me know.

**Comment by alefragnani** [comment]
@abierbaum it worked perfectly, thanks :+1:
