### ISSUE TITLE
Support for node's require paths

### ISSUE THREAD

**Issue by jmandzik** [abierbaum/vscode-file-peek#5]
Given `const performanceData = require('./performanceData');`  it can't find the file to peek/goto.  If I change it to `const performanceData = require('./performanceData.js');` it can.  It would be cool if this plugin could understand it was in a JS and/or require context and check for paths assuming a `.js` file extension.

**Comment by abierbaum** [comment]
@jmandzik I added support for file extension search options in version 1.0.0.  This should do what you are asking here and allow you to lookup .js or even .ts files.
