### ISSUE TITLE
Absolute Path is not working

### ISSUE THREAD

**Issue by ghost** [abierbaum/vscode-file-peek#7]
I do not quite know if this enforcement changed during angular development, but in my current environment i cannot go to file definition specified as absolute path (see screenshot below).
By default angular 2 requires absolute paths from the application root in the templateurl and styleurl paths. https://angular.io/docs/ts/latest/tutorial/toh-pt5.html.
If i change path to templateUrl: './hero-detail.component.html' (like in your preview), the file is found in the ide, but  you get a 

> GET http://localhost:3000/hero-detail.component.html 404 (Not Found)

If changed to templateUrl: 'app/hero-detail.component.html' it works in angular, but not in file peek.

![image](https://cloud.githubusercontent.com/assets/16099458/18661562/a7c304d6-7f16-11e6-8840-29f5252f12a8.png)

**Comment by abierbaum** [comment]
I am using webpack with Angular 2 which allows relative paths.  I have an idea how we could update it to find these style as well though.  Basically add a search path where first we check in the same directory as the file and then recurse up from there checking in each parent directory.

If you would like to give that a try, I would be very happy to accept a pull request.

**Comment by ghost** [comment]
That sounds reasonable. If I have time, i could have a look at it. But i am not firm in vs code scripting, so you are possibly faster :-)
